version: '3.8'

services:
  gitd-builder:
    image: gitd-builder:latest
    build:
      context: ./
      args:
        SERVICE_COMMIT_ID: ${SERVICE_COMMIT_ID}
        SERVICE_BUILD: ${SERVICE_BUILD}
    container_name: gitd-builder